### DISCUSSION TITLE
Use `TOML` files to save human-readable motion list configurations

### DISCUSSION THREAD

**Discussion by rocco8773** [BaPSF/bapsf_motion#71] [Ideas]
The idea is to use [`.toml` files](https://toml.io/en/) to save human-readable motion list and/or probe configuration parameters.  This is just an initial idea, so it can, and will likely, be expanded upon.  There already exists a python package [`toml`](https://github.com/uiri/toml) that can read and write these files; it is also [registered on PyPI](https://pypi.org/project/toml/).

The idea here is that you'd create a `<name>.toml` file where `<name>` will likely be the same as the data run, but could be anything.  The contents inside would look something like...

```toml
# idea for motionlist configuration
[ml.my_motionlist]   # "my_motionlist" is the name of the motionlist
units = "cm"  # units of configured values
coordinates = ["x", "y"]  # motion coordinates
shape = "rectangle"  # circle, sphere, etc.
size.x = 20  # size of the same, should be one for each in coordinates....this would be tricky for something like a polygon
size.y = 30
center.x = 0  # center position of the bounding area/volume
center.y = 2
grid.dx = 1  # start defining the grid resolution
grid.dy = 2
grid.start.x = 0  # starting point to build the grid off of
grid.start.y = 0.5

# idea for a probe configuration
[probe.my_probe]  # "my_probe" is the probe name
units = "cm"  # units of configuration values
port = 34  # port the probe is located
port.location = "E"  # E = East, could have west, top, bottom, etc.  ...which physical location on the port section
pivot = 52.4  # pivot distance from chamber center
shaft.OD = 0.9525  # diameter of probe shaft, would be useful for droop calculations
shaft.wall = 0.08128
motionlist = "my_motionlist"  # the motionlist paired to this probe
```

A few additional notes...

* A single file could contain multiple motionlists and/or probe configurations.
* The motion package should be able to read and write these files.
* The motion package would take read one of these files and then generate the array of points.  The should be achieved from both the DAQ and `bapsflib`.
* Some of these parameters could be optional and filled with default values at the time of reading.
* This framework also makes it easy for an individual to manually edit the `toml` file to quickly create a modified configuration from a previous one.
